# Generated by Django 4.0.4 on 2022-10-20 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('addressid', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('authorid', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('surname', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryid', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('organisationid', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('phonenumber', models.CharField(max_length=15)),
                ('organisationaddress', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.address')),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('paperid', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('papertitle', models.CharField(max_length=250)),
                ('paperurl', models.CharField(max_length=255)),
                ('authorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.author')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.category')),
            ],
        ),
        migrations.CreateModel(
            name='Postal_Address',
            fields=[
                ('postaladdressid', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('postalcode', models.IntegerField()),
                ('city', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('scheduleid', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('schedulename', models.CharField(max_length=250)),
                ('dataandtime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('titleid', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('venueid', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('capacity', models.IntegerField()),
                ('available', models.BooleanField()),
                ('addressid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.address')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=20)),
                ('firstname', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('affiliateorganisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.organisation')),
                ('title', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.title')),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('speakerid', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('profilepictureurl', models.CharField(max_length=255)),
                ('speakerorganisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('reviewid', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
                ('paperid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.paper')),
                ('reviewer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.user')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='postaladdressid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.postal_address'),
        ),
        migrations.CreateModel(
            name='Accomadation',
            fields=[
                ('roomid', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('roomphonenumber', models.CharField(max_length=20)),
                ('available', models.BooleanField()),
                ('tenant', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.user')),
            ],
        ),
    ]
